/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: Game_Off_2020_Outline.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @Game_Off_2020_Outline: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@Game_Off_2020_Outline()
	{
		this.StartPassage = "Logging On";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
		passage15_Init();
		passage16_Init();
		passage17_Init();
		passage18_Init();
		passage19_Init();
		passage20_Init();
		passage21_Init();
		passage22_Init();
		passage23_Init();
		passage24_Init();
		passage25_Init();
		passage26_Init();
		passage27_Init();
		passage28_Init();
		passage29_Init();
		passage30_Init();
		passage31_Init();
		passage32_Init();
		passage33_Init();
		passage34_Init();
		passage35_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Logging On

	void passage1_Init()
	{
		this.Passages[@"Logging On"] = new StoryPassage(@"Logging On", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("The player logs on, potentially playing a short \"boot up scene\" with sound effects (Think Windows boot up and the classic dial-up hum) and is brought to a web portal.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Home Scape", "Home Scape", null);
		yield return text(" ");
		yield return lineBreak();
		yield return link("Game Blast", "Game Blast", null);
		yield return lineBreak();
		yield return link("Cool Zone", "Cool Zone", null);
		yield return text(" ");
		yield return lineBreak();
		yield return link("Email", "Email", null);
		yield return text(" ");
		yield return lineBreak();
		yield return link("File Wire", "File Wire", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #2: Cool Zone

	void passage2_Init()
	{
		this.Passages[@"Cool Zone"] = new StoryPassage(@"Cool Zone", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("The player checks their social media/messenger feed.");
		yield break;
	}


	// .............
	// #3: Home Scape

	void passage3_Init()
	{
		this.Passages[@"Home Scape"] = new StoryPassage(@"Home Scape", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("The player checks their homepage featuring various news stories and clickbait articles.");
		yield break;
	}


	// .............
	// #4: Game Blast

	void passage4_Init()
	{
		this.Passages[@"Game Blast"] = new StoryPassage(@"Game Blast", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("The player signs into their video game forum account and checks some threads.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Game Blast Chat 1", "Game Blast Chat 1", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #5: Email

	void passage5_Init()
	{
		this.Passages[@"Email"] = new StoryPassage(@"Email", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("The player checks their email.");
		yield break;
	}


	// .............
	// #6: File Wire

	void passage6_Init()
	{
		this.Passages[@"File Wire"] = new StoryPassage(@"File Wire", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("The player downloads illicitly obtained media files.");
		yield break;
	}


	// .............
	// #7: Game Blast Chat 1

	void passage7_Init()
	{
		this.Passages[@"Game Blast Chat 1"] = new StoryPassage(@"Game Blast Chat 1", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("xXxsNiPeM@sTeRxXx: What's the best NEXT GEN console? I've been thinking of retiring my old Direct Box and upgrading to something else. Thanks!");
		yield return lineBreak();
		yield return link("SnideCooper's Reply", "SnideCooper's Reply", null);
		yield break;
	}


	// .............
	// #8: SnideCooper's Reply

	void passage8_Init()
	{
		this.Passages[@"SnideCooper's Reply"] = new StoryPassage(@"SnideCooper's Reply", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("SnideCooper: Tony Play Box. That's the best console if you say it isn't, you have worms for brains.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Calm Reply GB1", "Calm Reply GB1", null);
		yield return lineBreak();
		yield return link("Angry Reply GB1", "Angry Reply GB1", null);
		yield return lineBreak();
		yield return link("Sarcastic Reply GB1", "Sarcastic Reply GB1", null);
		yield return lineBreak();
		yield return link("Ignore GB1", "Ignore GB1", null);
		yield break;
	}


	// .............
	// #9: Calm Reply GB1

	void passage9_Init()
	{
		this.Passages[@"Calm Reply GB1"] = new StoryPassage(@"Calm Reply GB1", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("You: I respect SnideCooper's opinion, but I personally prefer the entertainment and value you get with the Funtendo Y!");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("+1 Fame");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("SnideCooper's Reply GB1", "SnideCooper's Reply GB1", null);
		yield break;
	}


	// .............
	// #10: Angry Reply GB1

	void passage10_Init()
	{
		this.Passages[@"Angry Reply GB1"] = new StoryPassage(@"Angry Reply GB1", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text("You: Well, the original, maybe, but the newest model, Tony Play Box 3 has next to no games. Phaze and Knick 2 are not worth $599.99, let alone their own $60 price tag.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("-1 Productivity");
		yield return lineBreak();
		yield return text("+1 Confidence");
		yield return lineBreak();
		yield return link("SnideCooper's Reply GB1", "SnideCooper's Reply GB1", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #11: Sarcastic Reply GB1

	void passage11_Init()
	{
		this.Passages[@"Sarcastic Reply GB1"] = new StoryPassage(@"Sarcastic Reply GB1", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return text("You: I also like to pay $600 for a paper weight.");
		yield return lineBreak();
		yield return text("+1 Fame");
		yield return lineBreak();
		yield return text("+1 Confidence");
		yield return lineBreak();
		yield return text("-1 Productivity");
		yield return lineBreak();
		yield return link("SnideCooper's Reply GB1", "SnideCooper's Reply GB1", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #12: Ignore GB1

	void passage12_Init()
	{
		this.Passages[@"Ignore GB1"] = new StoryPassage(@"Ignore GB1", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return text("(You choose to ignore this conversation)");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Waveracer2099: I think the Tony Game Box 3 and the Funtendo Y both have their merits! The Tony Game Box 3 has the potential for high definition gaming and media experiences that we just haven't seen before, but the Funtendo Y is bursting at the seams with creativity. I think it's worth grabbing either, OP, or even both consoles if you're working a second job, lol.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("+1 Productivity");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("(A message will show up from Waveracer2099 shortly after, for all intents and purposes, this conversation \"continues\" in )");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Waveracer2099's Cool Zone Message", "Waveracer2099's Cool Zone Message", null);
		yield break;
	}


	// .............
	// #13: SnideCooper's Reply GB1

	void passage13_Init()
	{
		this.Passages[@"SnideCooper's Reply GB1"] = new StoryPassage(@"SnideCooper's Reply GB1", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return text("SnideCooper: You're only saying that because you're a Funtendrone.");
		yield return lineBreak();
		yield return link("Calm Reply GB2", "Calm Reply GB2", null);
		yield return lineBreak();
		yield return link("Angry Reply GB2", "Angry Reply GB2", null);
		yield return lineBreak();
		yield return link("Sarcastic Reply GB2", "Sarcastic Reply GB2", null);
		yield return lineBreak();
		yield return link("Ignore GB1", "Ignore GB1", null);
		yield break;
	}


	// .............
	// #14: Calm Reply GB2

	void passage14_Init()
	{
		this.Passages[@"Calm Reply GB2"] = new StoryPassage(@"Calm Reply GB2", new string[]{  }, passage14_Main);
	}

	IStoryThread passage14_Main()
	{
		yield return text("You: Haha, we prefer Funtendo Fans or Fantendos. Okay, no, that second one is pretty bad.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("+1 Fame");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("SnideCooper's Reply GB3", "SnideCooper's Reply GB3", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #15: Angry Reply GB2

	void passage15_Init()
	{
		this.Passages[@"Angry Reply GB2"] = new StoryPassage(@"Angry Reply GB2", new string[]{  }, passage15_Main);
	}

	IStoryThread passage15_Main()
	{
		yield return text("You: I'm only saying that because I like to play games that aren't shit.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("+1 Confidence");
		yield return lineBreak();
		yield return text("-1 Productivity");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("SnideCooper's Reply GB3", "SnideCooper's Reply GB3", null);
		yield break;
	}


	// .............
	// #16: Sarcastic Reply GB2

	void passage16_Init()
	{
		this.Passages[@"Sarcastic Reply GB2"] = new StoryPassage(@"Sarcastic Reply GB2", new string[]{  }, passage16_Main);
	}

	IStoryThread passage16_Main()
	{
		yield return text("You: I'm the drone, yet you're the one producing an automated response.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("+1 Fame");
		yield return lineBreak();
		yield return text("+1 Confidence");
		yield return lineBreak();
		yield return text("-1 Productivity");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("SnideCooper's Reply GB3", "SnideCooper's Reply GB3", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #17: Waveracer2099's Cool Zone Message

	void passage17_Init()
	{
		this.Passages[@"Waveracer2099's Cool Zone Message"] = new StoryPassage(@"Waveracer2099's Cool Zone Message", new string[]{  }, passage17_Main);
	}

	IStoryThread passage17_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


	// .............
	// #18: SnideCooper's Reply GB3

	void passage18_Init()
	{
		this.Passages[@"SnideCooper's Reply GB3"] = new StoryPassage(@"SnideCooper's Reply GB3", new string[]{  }, passage18_Main);
	}

	IStoryThread passage18_Main()
	{
		yield return text("SnideCooper: Go play Superb Guys 1937 (Which hasn't even been good in years) and I will play my games which actually require an IQ to understand.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Angry/Sarcastic Reply GB3", "Angry/Sarcastic Reply GB3", null);
		yield return lineBreak();
		yield return link("Calm Reply GB3", "Calm Reply GB3", null);
		yield return lineBreak();
		yield return link("Ignore GB1", "Ignore GB1", null);
		yield break;
	}


	// .............
	// #19: Angry/Sarcastic Reply GB3

	void passage19_Init()
	{
		this.Passages[@"Angry/Sarcastic Reply GB3"] = new StoryPassage(@"Angry/Sarcastic Reply GB3", new string[]{  }, passage19_Main);
	}

	IStoryThread passage19_Main()
	{
		yield return text("You: Yeah, a low IQ.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("+1 Fame");
		yield return lineBreak();
		yield return text("+1 Confidence");
		yield return lineBreak();
		yield return text("-2 Productivity");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("SnideCooper's Reply GB4", "SnideCooper's Reply GB4", null);
		yield break;
	}


	// .............
	// #20: Calm Reply GB3

	void passage20_Init()
	{
		this.Passages[@"Calm Reply GB3"] = new StoryPassage(@"Calm Reply GB3", new string[]{  }, passage20_Main);
	}

	IStoryThread passage20_Main()
	{
		yield return text("You: Have you tried New Superb Guys Universe? It's genuinely really good and I think you might like it!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("SnideCooper's Reply GB7", "SnideCooper's Reply GB7", null);
		yield break;
	}


	// .............
	// #21: SnideCooper's Reply GB4

	void passage21_Init()
	{
		this.Passages[@"SnideCooper's Reply GB4"] = new StoryPassage(@"SnideCooper's Reply GB4", new string[]{  }, passage21_Main);
	}

	IStoryThread passage21_Main()
	{
		yield return text("SnideCooper: When was the last time they even made a new IP? 20 years ago?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Calm Reply GB4", "Calm Reply GB4", null);
		yield return lineBreak();
		yield return link("Angry Reply GB4", "Angry Reply GB4", null);
		yield return lineBreak();
		yield return link("Sarcastic Reply GB4", "Sarcastic Reply GB4", null);
		yield return lineBreak();
		yield return link("Ignore GB1", "Ignore GB1", null);
		yield break;
	}


	// .............
	// #22: SnideCooper's Reply GB7

	void passage22_Init()
	{
		this.Passages[@"SnideCooper's Reply GB7"] = new StoryPassage(@"SnideCooper's Reply GB7", new string[]{  }, passage22_Main);
	}

	IStoryThread passage22_Main()
	{
		yield return text("SnideCooper: Superb Guys wasn't even as good a Wack Wallaby.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Calm Reply GB7", "Calm Reply GB7", null);
		yield return lineBreak();
		yield return link("Angry/Sarcastic Reply GB7", "Angry/Sarcastic Reply GB7", null);
		yield return lineBreak();
		yield return link("Ignore GB2", "Ignore GB2", null);
		yield break;
	}


	// .............
	// #23: Calm Reply GB4

	void passage23_Init()
	{
		this.Passages[@"Calm Reply GB4"] = new StoryPassage(@"Calm Reply GB4", new string[]{  }, passage23_Main);
	}

	IStoryThread passage23_Main()
	{
		yield return text("You: Brain Bug and Funtendogs were HUGE on the Funtendo GS! Not to mention the slightly more obscure hits like Fire Heart Pep Squad and Father III.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("+1 Fame");
		yield return lineBreak();
		yield return text("-1 Productivity");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("SnideCooper's Reply GB5", "SnideCooper's Reply GB5", null);
		yield break;
	}


	// .............
	// #24: Angry Reply GB4

	void passage24_Init()
	{
		this.Passages[@"Angry Reply GB4"] = new StoryPassage(@"Angry Reply GB4", new string[]{  }, passage24_Main);
	}

	IStoryThread passage24_Main()
	{
		yield return text("You: I see you are COMPLETELY ignoring the Funtendo GS.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("+1 Confidence");
		yield return lineBreak();
		yield return text("-1 Productivity");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("SnideCooper's Reply GB5", "SnideCooper's Reply GB5", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #25: Sarcastic Reply GB4

	void passage25_Init()
	{
		this.Passages[@"Sarcastic Reply GB4"] = new StoryPassage(@"Sarcastic Reply GB4", new string[]{  }, passage25_Main);
	}

	IStoryThread passage25_Main()
	{
		yield return text("You: You don't really need to make eight new IP's a month when you have actually good ones to begin with.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("+1 Confidence");
		yield return lineBreak();
		yield return text("-1 Productivity");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("SnideCooper's Reply GB7", "SnideCooper's Reply GB7", null);
		yield break;
	}


	// .............
	// #26: SnideCooper's Reply GB5

	void passage26_Init()
	{
		this.Passages[@"SnideCooper's Reply GB5"] = new StoryPassage(@"SnideCooper's Reply GB5", new string[]{  }, passage26_Main);
	}

	IStoryThread passage26_Main()
	{
		yield return text("SnideCooper: My little sister has one of those, it's literally for babies and grandmas");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Calm Reply GB5", "Calm Reply GB5", null);
		yield return lineBreak();
		yield return link("Angry/Sarcastic Reply GB5", "Angry/Sarcastic Reply GB5", null);
		yield return lineBreak();
		yield return link("Ignore GB2", "Ignore GB2", null);
		yield break;
	}


	// .............
	// #27: Calm Reply GB5

	void passage27_Init()
	{
		this.Passages[@"Calm Reply GB5"] = new StoryPassage(@"Calm Reply GB5", new string[]{  }, passage27_Main);
	}

	IStoryThread passage27_Main()
	{
		yield return text("You: If your sister ever wants to play Superb Guys with me, my Friend Code is 5346 8050 4311!");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("+1 Fame");
		yield return lineBreak();
		yield return text("+1 Happiness");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Waveracer2099's Cool Zone Message", "Waveracer2099's Cool Zone Message", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #28: Angry/Sarcastic Reply GB5

	void passage28_Init()
	{
		this.Passages[@"Angry/Sarcastic Reply GB5"] = new StoryPassage(@"Angry/Sarcastic Reply GB5", new string[]{  }, passage28_Main);
	}

	IStoryThread passage28_Main()
	{
		yield return text("You: Surprised you're related to someone whose brain isn't cnacer. Figured it was genetic.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("-1 Fame");
		yield return lineBreak();
		yield return text("-1 Productivity");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("SnideCooper's Reply GB7", "SnideCooper's Reply GB7", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #29: Ignore GB2

	void passage29_Init()
	{
		this.Passages[@"Ignore GB2"] = new StoryPassage(@"Ignore GB2", new string[]{  }, passage29_Main);
	}

	IStoryThread passage29_Main()
	{
		yield return text("(Upon ending your conversation with them, SnideCooper emails you, as your email is available as part of your public profile)");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("+1 Productivity");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("SnideCooper's Email", "SnideCooper's Email", null);
		yield break;
	}


	// .............
	// #30: SnideCooper's Email

	void passage30_Init()
	{
		this.Passages[@"SnideCooper's Email"] = new StoryPassage(@"SnideCooper's Email", new string[]{  }, passage30_Main);
	}

	IStoryThread passage30_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


	// .............
	// #31: Calm Reply GB7

	void passage31_Init()
	{
		this.Passages[@"Calm Reply GB7"] = new StoryPassage(@"Calm Reply GB7", new string[]{  }, passage31_Main);
	}

	IStoryThread passage31_Main()
	{
		yield return text("You: How is Wack Wallaby these days?");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("-1 Productivity");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("SnideCooper's Reply GB8", "SnideCooper's Reply GB8", null);
		yield break;
	}


	// .............
	// #32: Angry/Sarcastic Reply GB7

	void passage32_Init()
	{
		this.Passages[@"Angry/Sarcastic Reply GB7"] = new StoryPassage(@"Angry/Sarcastic Reply GB7", new string[]{  }, passage32_Main);
	}

	IStoryThread passage32_Main()
	{
		yield return text("You: Why don't you go wack your wallaby?");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("+1 Fame");
		yield return lineBreak();
		yield return text("-2 Productivity");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Banned Message GB1", "Banned Message GB1", null);
		yield break;
	}


	// .............
	// #33: Banned Message GB1

	void passage33_Init()
	{
		this.Passages[@"Banned Message GB1"] = new StoryPassage(@"Banned Message GB1", new string[]{  }, passage33_Main);
	}

	IStoryThread passage33_Main()
	{
		yield return text("Admin: You have been banned from this forum for two weeks for poor behavior.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("(You recieve an email from SnideCooper as your email is a part of your public profile)");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("SnideCooper's Email Banned Alt", "SnideCooper's Email Banned Alt", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #34: SnideCooper's Reply GB8

	void passage34_Init()
	{
		this.Passages[@"SnideCooper's Reply GB8"] = new StoryPassage(@"SnideCooper's Reply GB8", new string[]{  }, passage34_Main);
	}

	IStoryThread passage34_Main()
	{
		yield return text("SnideCooper: Last year's remake was a best seller, DUMBASS!");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("(You recieve an email from SnideCooper as your email is on your public profile)");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("SnideCooper's Email Banned Alt", "SnideCooper's Email Banned Alt", null);
		yield break;
	}


	// .............
	// #35: SnideCooper's Email Banned Alt

	void passage35_Init()
	{
		this.Passages[@"SnideCooper's Email Banned Alt"] = new StoryPassage(@"SnideCooper's Email Banned Alt", new string[]{  }, passage35_Main);
	}

	IStoryThread passage35_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


}